{% set version = "2017.07.28" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 27ab18243b1a0aa1467027be93b118c9fcd60dd2e4020da579fad3008bc4638f

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python-2.0
  license_family: PSF
  summary: 'Alternative regular expression module, to replace re'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
